const GET_SELLER = "GET_SELLER"
const GET_GOODS = "GET_GOODS"
const DETAIL_SHOW = "DETAIL_SHOW"
const DETAIL_HIDE = "DETAIL_HIDE"
const GET_NAME = "GET_NAME"

export default {
	GET_SELLER,
	GET_GOODS,
	DETAIL_SHOW,
	DETAIL_HIDE,
	GET_NAME
}